### ISSUE TITLE
md5checksum differences between nodes

### ISSUE THREAD

**Issue by diego-rt** [a-ludi/dentist#26]
Hi Arne,

I hope you are well. First of all congrats on the very exciting tool, I'm really looking forward to try it out on my ultra long Nanopore data! 

However, I'm having a bit of trouble getting dentist set up. For starters, the example dataset only gets the md5 checksums right when I run it on a specific high memory node and not in any of our other computing nodes. In addition, this only works when used together with your singularity image and not with the bundled binaries in the bin folder of the example dataset.

Also, when I run it through slurm, there's yet an additional problem in that it reproducibly stops right after the collect check point and I need to run it again to finish the rest of the process. I'm not sure whether this might be due to the first issue since I haven't been able to queue it to that specific node but I'm in the process of checking.

Any ideas about where the problem might lie? 

Thanks!!

### Succesfull node (high memory)
```
[diego.terrones@clip-m1-0 dentist-example]$ md5sum -c checksum.md5
gap-closed.closed-gaps.bed: OK
gap-closed.fasta: OK
workdir/.assembly-test.bps: OK
workdir/.assembly-test.dentist-reads-H.anno: OK
workdir/.assembly-test.dentist-reads-H.data: OK
workdir/.assembly-test.dentist-reads.anno: OK
workdir/.assembly-test.dentist-reads.data: OK
workdir/.assembly-test.dentist-self-H.anno: OK
workdir/.assembly-test.dentist-self-H.data: OK
workdir/.assembly-test.dentist-self.anno: OK
workdir/.assembly-test.dentist-self.data: OK
workdir/.assembly-test.dust.anno: OK
workdir/.assembly-test.dust.data: OK
workdir/.assembly-test.hdr: OK
workdir/.assembly-test.idx: OK
workdir/.assembly-test.tan-H.anno: OK
workdir/.assembly-test.tan-H.data: OK
workdir/.assembly-test.tan.anno: OK
workdir/.assembly-test.tan.data: OK
workdir/.gap-closed-preliminary.bps: OK
workdir/.gap-closed-preliminary.closed-gaps.anno: OK
workdir/.gap-closed-preliminary.closed-gaps.data: OK
workdir/.gap-closed-preliminary.dentist-self.anno: OK
workdir/.gap-closed-preliminary.dentist-self.data: OK
workdir/.gap-closed-preliminary.dentist-weak-coverage.anno: OK
workdir/.gap-closed-preliminary.dentist-weak-coverage.data: OK
workdir/.gap-closed-preliminary.dust.anno: OK
workdir/.gap-closed-preliminary.dust.data: OK
workdir/.gap-closed-preliminary.hdr: OK
workdir/.gap-closed-preliminary.idx: OK
workdir/.gap-closed-preliminary.tan.anno: OK
workdir/.gap-closed-preliminary.tan.data: OK
workdir/.reads.bps: OK
workdir/.reads.dentist-reads-10B.anno: OK
workdir/.reads.dentist-reads-10B.data: OK
workdir/.reads.dentist-reads-11B.anno: OK
workdir/.reads.dentist-reads-11B.data: OK
workdir/.reads.dentist-reads-12B.anno: OK
workdir/.reads.dentist-reads-12B.data: OK
workdir/.reads.dentist-reads-1B.anno: OK
workdir/.reads.dentist-reads-1B.data: OK
workdir/.reads.dentist-reads-2B.anno: OK
workdir/.reads.dentist-reads-2B.data: OK
workdir/.reads.dentist-reads-3B.anno: OK
workdir/.reads.dentist-reads-3B.data: OK
workdir/.reads.dentist-reads-4B.anno: OK
workdir/.reads.dentist-reads-4B.data: OK
workdir/.reads.dentist-reads-5B.anno: OK
workdir/.reads.dentist-reads-5B.data: OK
workdir/.reads.dentist-reads-6B.anno: OK
workdir/.reads.dentist-reads-6B.data: OK
workdir/.reads.dentist-reads-7B.anno: OK
workdir/.reads.dentist-reads-7B.data: OK
workdir/.reads.dentist-reads-8B.anno: OK
workdir/.reads.dentist-reads-8B.data: OK
workdir/.reads.dentist-reads-9B.anno: OK
workdir/.reads.dentist-reads-9B.data: OK
workdir/.reads.dentist-self-10B.anno: OK
workdir/.reads.dentist-self-10B.data: OK
workdir/.reads.dentist-self-11B.anno: OK
workdir/.reads.dentist-self-11B.data: OK
workdir/.reads.dentist-self-12B.anno: OK
workdir/.reads.dentist-self-12B.data: OK
workdir/.reads.dentist-self-1B.anno: OK
workdir/.reads.dentist-self-1B.data: OK
workdir/.reads.dentist-self-2B.anno: OK
workdir/.reads.dentist-self-2B.data: OK
workdir/.reads.dentist-self-3B.anno: OK
workdir/.reads.dentist-self-3B.data: OK
workdir/.reads.dentist-self-4B.anno: OK
workdir/.reads.dentist-self-4B.data: OK
workdir/.reads.dentist-self-5B.anno: OK
workdir/.reads.dentist-self-5B.data: OK
workdir/.reads.dentist-self-6B.anno: OK
workdir/.reads.dentist-self-6B.data: OK
workdir/.reads.dentist-self-7B.anno: OK
workdir/.reads.dentist-self-7B.data: OK
workdir/.reads.dentist-self-8B.anno: OK
workdir/.reads.dentist-self-8B.data: OK
workdir/.reads.dentist-self-9B.anno: OK
workdir/.reads.dentist-self-9B.data: OK
workdir/.reads.idx: OK
workdir/.reads.tan-10B.anno: OK
workdir/.reads.tan-10B.data: OK
workdir/.reads.tan-11B.anno: OK
workdir/.reads.tan-11B.data: OK
workdir/.reads.tan-12B.anno: OK
workdir/.reads.tan-12B.data: OK
workdir/.reads.tan-1B.anno: OK
workdir/.reads.tan-1B.data: OK
workdir/.reads.tan-2B.anno: OK
workdir/.reads.tan-2B.data: OK
workdir/.reads.tan-3B.anno: OK
workdir/.reads.tan-3B.data: OK
workdir/.reads.tan-4B.anno: OK
workdir/.reads.tan-4B.data: OK
workdir/.reads.tan-5B.anno: OK
workdir/.reads.tan-5B.data: OK
workdir/.reads.tan-6B.anno: OK
workdir/.reads.tan-6B.data: OK
workdir/.reads.tan-7B.anno: OK
workdir/.reads.tan-7B.data: OK
workdir/.reads.tan-8B.anno: OK
workdir/.reads.tan-8B.data: OK
workdir/.reads.tan-9B.anno: OK
workdir/.reads.tan-9B.data: OK
workdir/assembly-test.dam: OK
workdir/gap-closed-preliminary.dam: OK
workdir/gap-closed-preliminary.fasta: OK
workdir/reads.db: OK
workdir/validation-report.json: OK

```

### Config

```
[diego.terrones@clip-m1-0 dentist-example]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core
[diego.terrones@clip-m1-0 dentist-example]$ free -h
              total        used        free      shared  buff/cache   available
Mem:           1.9T        943G        938G         89M         55G        991G
Swap:            0B          0B          0B

```

### All other nodes

```
[diego.terrones@clip-c2-2 dentist-example]$ md5sum -c checksum.md5
gap-closed.closed-gaps.bed: FAILED
gap-closed.fasta: FAILED
workdir/.assembly-test.bps: OK
workdir/.assembly-test.dentist-reads-H.anno: OK
workdir/.assembly-test.dentist-reads-H.data: OK
workdir/.assembly-test.dentist-reads.anno: OK
workdir/.assembly-test.dentist-reads.data: OK
workdir/.assembly-test.dentist-self-H.anno: OK
workdir/.assembly-test.dentist-self-H.data: OK
workdir/.assembly-test.dentist-self.anno: OK
workdir/.assembly-test.dentist-self.data: OK
workdir/.assembly-test.dust.anno: OK
workdir/.assembly-test.dust.data: OK
workdir/.assembly-test.hdr: OK
workdir/.assembly-test.idx: OK
workdir/.assembly-test.tan-H.anno: OK
workdir/.assembly-test.tan-H.data: OK
workdir/.assembly-test.tan.anno: OK
workdir/.assembly-test.tan.data: OK
workdir/.gap-closed-preliminary.bps: FAILED
workdir/.gap-closed-preliminary.closed-gaps.anno: FAILED
workdir/.gap-closed-preliminary.closed-gaps.data: FAILED
workdir/.gap-closed-preliminary.dentist-self.anno: FAILED
workdir/.gap-closed-preliminary.dentist-self.data: FAILED
workdir/.gap-closed-preliminary.dentist-weak-coverage.anno: FAILED
workdir/.gap-closed-preliminary.dentist-weak-coverage.data: OK
workdir/.gap-closed-preliminary.dust.anno: FAILED
workdir/.gap-closed-preliminary.dust.data: FAILED
workdir/.gap-closed-preliminary.hdr: OK
workdir/.gap-closed-preliminary.idx: FAILED
workdir/.gap-closed-preliminary.tan.anno: FAILED
workdir/.gap-closed-preliminary.tan.data: FAILED
workdir/.reads.bps: OK
workdir/.reads.dentist-reads-10B.anno: OK
workdir/.reads.dentist-reads-10B.data: OK
workdir/.reads.dentist-reads-11B.anno: OK
workdir/.reads.dentist-reads-11B.data: OK
workdir/.reads.dentist-reads-12B.anno: OK
workdir/.reads.dentist-reads-12B.data: OK
workdir/.reads.dentist-reads-1B.anno: OK
workdir/.reads.dentist-reads-1B.data: OK
workdir/.reads.dentist-reads-2B.anno: OK
workdir/.reads.dentist-reads-2B.data: OK
workdir/.reads.dentist-reads-3B.anno: OK
workdir/.reads.dentist-reads-3B.data: OK
workdir/.reads.dentist-reads-4B.anno: OK
workdir/.reads.dentist-reads-4B.data: OK
workdir/.reads.dentist-reads-5B.anno: OK
workdir/.reads.dentist-reads-5B.data: OK
workdir/.reads.dentist-reads-6B.anno: OK
workdir/.reads.dentist-reads-6B.data: OK
workdir/.reads.dentist-reads-7B.anno: OK
workdir/.reads.dentist-reads-7B.data: OK
workdir/.reads.dentist-reads-8B.anno: OK
workdir/.reads.dentist-reads-8B.data: OK
workdir/.reads.dentist-reads-9B.anno: OK
workdir/.reads.dentist-reads-9B.data: OK
workdir/.reads.dentist-self-10B.anno: OK
workdir/.reads.dentist-self-10B.data: OK
workdir/.reads.dentist-self-11B.anno: OK
workdir/.reads.dentist-self-11B.data: OK
workdir/.reads.dentist-self-12B.anno: OK
workdir/.reads.dentist-self-12B.data: OK
workdir/.reads.dentist-self-1B.anno: OK
workdir/.reads.dentist-self-1B.data: OK
workdir/.reads.dentist-self-2B.anno: OK
workdir/.reads.dentist-self-2B.data: OK
workdir/.reads.dentist-self-3B.anno: OK
workdir/.reads.dentist-self-3B.data: OK
workdir/.reads.dentist-self-4B.anno: OK
workdir/.reads.dentist-self-4B.data: OK
workdir/.reads.dentist-self-5B.anno: OK
workdir/.reads.dentist-self-5B.data: OK
workdir/.reads.dentist-self-6B.anno: OK
workdir/.reads.dentist-self-6B.data: OK
workdir/.reads.dentist-self-7B.anno: OK
workdir/.reads.dentist-self-7B.data: OK
workdir/.reads.dentist-self-8B.anno: OK
workdir/.reads.dentist-self-8B.data: OK
workdir/.reads.dentist-self-9B.anno: OK
workdir/.reads.dentist-self-9B.data: OK
workdir/.reads.idx: OK
workdir/.reads.tan-10B.anno: OK
workdir/.reads.tan-10B.data: OK
workdir/.reads.tan-11B.anno: OK
workdir/.reads.tan-11B.data: OK
workdir/.reads.tan-12B.anno: OK
workdir/.reads.tan-12B.data: OK
workdir/.reads.tan-1B.anno: OK
workdir/.reads.tan-1B.data: OK
workdir/.reads.tan-2B.anno: OK
workdir/.reads.tan-2B.data: OK
workdir/.reads.tan-3B.anno: OK
workdir/.reads.tan-3B.data: OK
workdir/.reads.tan-4B.anno: OK
workdir/.reads.tan-4B.data: OK
workdir/.reads.tan-5B.anno: OK
workdir/.reads.tan-5B.data: OK
workdir/.reads.tan-6B.anno: OK
workdir/.reads.tan-6B.data: OK
workdir/.reads.tan-7B.anno: OK
workdir/.reads.tan-7B.data: OK
workdir/.reads.tan-8B.anno: OK
workdir/.reads.tan-8B.data: OK
workdir/.reads.tan-9B.anno: OK
workdir/.reads.tan-9B.data: OK
workdir/assembly-test.dam: OK
workdir/gap-closed-preliminary.dam: FAILED
workdir/gap-closed-preliminary.fasta: FAILED
workdir/reads.db: OK
workdir/validation-report.json: OK
md5sum: WARNING: 15 computed checksums did NOT match
```

**Comment by a-ludi** [comment]
Hi Diego,

can check if you are using the latest version of DENTIST and the example? Here is the expected output if using Singularity:

```
$ singularity exec docker://aludi/dentist:stable dentist --version
dentist v2.0.0 (commit e7659a9f23178c952b21da14da72f1aa6a812675)

Copyright © 2018, Arne Ludwig <arne.ludwig@posteo.de>

Subject to the terms of the MIT license, as written in the included LICENSE file

```

If you get a different version please clean your Singularity cache with

```
$ singularity cache clean -T oci --name dentist_stable.sif
This will delete everything in your cache (containers from all sources and OCI blobs). 
Hint: You can see exactly what would be deleted by canceling and using the --dry-run option.
Do you want to continue? [N/y] y
Removing /home/a-ludi/.singularity/cache/cache/oci-tmp/3c6fdfdea388b95d5940f2623c316f44dd1a27b990bb7c61a02d4f4363ca94ed/dentist_stable.sif
```

This should delete exactly one file. Afterwards try running the version command from above. This should trigger a download of the latest version and give you the expected output.

Regarding the binaries, I want to make sure you are using the latest version as well:

```
$ PATH="$PWD/bin:$PATH" dentist --version
dentist v2.0.0 (commit e7659a9f23178c952b21da14da72f1aa6a812675)

Copyright © 2018, Arne Ludwig <arne.ludwig@posteo.de>

Subject to the terms of the MIT license, as written in the included LICENSE file
```

If this gives the wrong version, you are using an old version of the example dataset. Just [download the latest version](https://github.com/a-ludi/dentist-example/releases/download/v2.0.0-2/dentist-example.tar.gz) and try again.

I hope this already helps. If you have any more issues please feel free to ask for more help.

-- Arne

**Comment by diego-rt** [comment]
Hi Arne,

Thanks a lot for your quick reply!!

Unfortunately seems like all version are current. The example is the most recent one from the release section from your repository and the container is the one found within, which as far as I understand it should not have been pulled from the singularity cache as the filename is explicitly outlined in your snakemake.yml file. 

Here are the commands (and the resulting logs) that I've run:

```
#Download your test example
[diego.terrones@clip-login-1 dentist-example]$ wget -O dentist-example_v2.0.0-2.tar.gz https://github.com/a-ludi/dentist-example/releases/download/v2.0.0-2/dentist-example.tar.gz

#unpack
[diego.terrones@clip-login-1 dentist-example]$ tar -xvzf dentist-example_v2.0.0-2.tar.gz 
[diego.terrones@clip-login-1 dentist-example]$ cd dentist-example/

#check version for bins
[diego.terrones@clip-login-1 dentist-example]$ PATH="$PWD/bin:$PATH" dentist --version
dentist v2.0.0 (commit e7659a9f23178c952b21da14da72f1aa6a812675)

Copyright © 2018, Arne Ludwig <arne.ludwig@posteo.de>

Subject to the terms of the MIT license, as written in the included LICENSE file

#check version for container in example dir
[diego.terrones@clip-login-1 dentist-example]$ singularity exec dentist_v2.0.0.sif dentist --version
dentist v2.0.0 (commit e7659a9f23178c952b21da14da72f1aa6a812675)

Copyright © 2018, Arne Ludwig <arne.ludwig@posteo.de>

Subject to the terms of the MIT license, as written in the included LICENSE file

#The snakelike file points to the sif file in the current directory so the singularity cache is unlikely to be an issue
[diego.terrones@clip-login-1 dentist-example]$ cat snakemake.yml 
# You may provide default values for environment variable. They will only be
# used if the variable is undefined in the current environment.
#default_env:
#    TMPDIR: /home/user/tmp

# You may also override values in the environment.
#override_env:
#    LANG:   C


# --- Environment variables substitution ---
#
# Environment variables may be referenced in the config via `$VARNAME` or
# `${VARNAME}`; to get a literal dollar sign use `$$`. Values in `deafult_env`
# `override_env` are expanded with the unmodified environment.
#
# Beware, if using environment variables in `dentist_config` the data type
# must be correct, e.g. you cannot pass `read-coverage` be environment
# variable because it will be a string but a float is expected. Still, if you
# specify values via `env` in the config then they will keep their data type,
# so the following will work:
#
#     override_env:
#         COV: 30.0
#     dentist_config:
#         __default__:
#             read-coverage: $COV


# Uncomment the follow workflow flags to alter the workflow

# Add the validation report and weak coverage mask to the list of default
# targets so they will be generated wether or not they are required to build
# the main target (gap-closed assembly)
full_validation: true

# By default the closed gaps will be validated and only valid gaps will be
# included into the final gap-closed assembly. Give this flag to get the
# raw gap-closed assembly as final output.
#no_purge_output: true

# The workflow can be easily run inside a container (--use-singularity) to
# reduce the software installations. The default container is
# "docker://aludi/dentist:stable" and can be changed by the following line.
dentist_container: dentist_v2.0.0.sif


inputs:
    # The reference assembly where gaps should be closed
    reference:          data/assembly-test.fasta
    # The set of long reads used for gap closing
    reads:              data/reads.fasta
    # Type of reads. Use `PACBIO_SMRT` or `OXFORD_NANOPORE`. See README for
    # more details on the subject.
    reads_type:         PACBIO_SMRT

outputs:
    # The gap-closed reference assembly
    output_assembly:    gap-closed.fasta
    # JSON file with a validation report for each closed gap
    #validation_report:  $workdir/validation-report.json

reference_dbsplit:
    - -x1000
    - -a
    - -s50
reads_dbsplit:
    - -x1000
    - -a
    - -s50

# Directories for intermediate and log files.
workdir:            workdir
logdir:             logs

# Workflow files that are created inside of workdir; uncomment and adjust if
# you feel the need
#workflow:
#    self_mask:          dentist-self
#    reads_mask:         dentist-reads
#    pile_ups:           pile-ups.db
#    insertions_batch:   insertions/batch.{batch_id}.db
#    dentist_merge_config_file: dentist.merge.json
#    insertions:         insertions.db
#    closed_gaps_mask:   closed-gaps
#    weak_coverage_mask: dentist-weak-coverage

# Maximum number of threads to use
max_threads:        8

# Number of threads to use for auxiliary commands such as daligner or daccord.
# Defaults to max(1, threads // 4)
#auxiliary_threads: 1

# Masks are propagated from the assembly to the reads and back in batches
# of read DB blocks. This makes cluster jobs run for at least a few minutes
# as each block usually just takes much less than a minute.
propagate_batch_size: 14

# Insertions are generated in batches of `batch_size`; use lower number to
# shorten the runtime of each job while increasing the number of jobs.
batch_size:         50

# Validation is split into this number of similar-sized parts of the
# gap-closed vs reads alignment. If the number of blocks is higher than the
# number of contigs in the gap-closed assembly then some validation runs will
# do nothing.
validation_blocks:  2


#edit cluster.yml to change partition name to our standard computing one
[diego.terrones@clip-login-1 dentist-example]$ vi cluster.yml 

#launch pipeline with latency wait (was getting errors without it regarding files not found)
[diego.terrones@clip-login-1 dentist-example]$ snakemake --configfile=snakemake.yml --use-singularity --profile=slurm --latency-wait 30

### Output -> Log1.txt ; Have to re-run pipeline to complete
[Log1.txt](https://github.com/a-ludi/dentist/files/7079160/Log1.txt)

[diego.terrones@clip-login-1 dentist-example]$ snakemake --configfile=snakemake.yml --use-singularity --profile=slurm --latency-wait 30

### Output -> Log2
[Log2.txt](https://github.com/a-ludi/dentist/files/7079159/Log2.txt)

[diego.terrones@clip-login-1 dentist-example]$ md5sum -c checksum.md5
gap-closed.closed-gaps.bed: FAILED
gap-closed.fasta: FAILED
workdir/.assembly-test.bps: OK
workdir/.assembly-test.dentist-reads-H.anno: FAILED
workdir/.assembly-test.dentist-reads-H.data: FAILED
workdir/.assembly-test.dentist-reads.anno: OK
workdir/.assembly-test.dentist-reads.data: OK
workdir/.assembly-test.dentist-self-H.anno: FAILED
workdir/.assembly-test.dentist-self-H.data: FAILED
workdir/.assembly-test.dentist-self.anno: OK
workdir/.assembly-test.dentist-self.data: OK
workdir/.assembly-test.dust.anno: OK
workdir/.assembly-test.dust.data: OK
workdir/.assembly-test.hdr: OK
workdir/.assembly-test.idx: OK
workdir/.assembly-test.tan-H.anno: FAILED
workdir/.assembly-test.tan-H.data: FAILED
workdir/.assembly-test.tan.anno: OK
workdir/.assembly-test.tan.data: OK
workdir/.gap-closed-preliminary.bps: FAILED
workdir/.gap-closed-preliminary.closed-gaps.anno: FAILED
workdir/.gap-closed-preliminary.closed-gaps.data: FAILED
workdir/.gap-closed-preliminary.dentist-self.anno: FAILED
workdir/.gap-closed-preliminary.dentist-self.data: FAILED
workdir/.gap-closed-preliminary.dentist-weak-coverage.anno: FAILED
workdir/.gap-closed-preliminary.dentist-weak-coverage.data: OK
workdir/.gap-closed-preliminary.dust.anno: FAILED
workdir/.gap-closed-preliminary.dust.data: FAILED
workdir/.gap-closed-preliminary.hdr: OK
workdir/.gap-closed-preliminary.idx: FAILED
workdir/.gap-closed-preliminary.tan.anno: FAILED
workdir/.gap-closed-preliminary.tan.data: FAILED
workdir/.reads.bps: OK
workdir/.reads.dentist-reads-10B.anno: OK
workdir/.reads.dentist-reads-10B.data: OK
workdir/.reads.dentist-reads-11B.anno: OK
workdir/.reads.dentist-reads-11B.data: OK
workdir/.reads.dentist-reads-12B.anno: OK
workdir/.reads.dentist-reads-12B.data: OK
workdir/.reads.dentist-reads-1B.anno: OK
workdir/.reads.dentist-reads-1B.data: OK
workdir/.reads.dentist-reads-2B.anno: OK
workdir/.reads.dentist-reads-2B.data: OK
workdir/.reads.dentist-reads-3B.anno: OK
workdir/.reads.dentist-reads-3B.data: OK
workdir/.reads.dentist-reads-4B.anno: OK
workdir/.reads.dentist-reads-4B.data: OK
workdir/.reads.dentist-reads-5B.anno: OK
workdir/.reads.dentist-reads-5B.data: OK
workdir/.reads.dentist-reads-6B.anno: OK
workdir/.reads.dentist-reads-6B.data: OK
workdir/.reads.dentist-reads-7B.anno: OK
workdir/.reads.dentist-reads-7B.data: OK
workdir/.reads.dentist-reads-8B.anno: OK
workdir/.reads.dentist-reads-8B.data: OK
workdir/.reads.dentist-reads-9B.anno: OK
workdir/.reads.dentist-reads-9B.data: OK
workdir/.reads.dentist-self-10B.anno: OK
workdir/.reads.dentist-self-10B.data: OK
workdir/.reads.dentist-self-11B.anno: OK
workdir/.reads.dentist-self-11B.data: OK
workdir/.reads.dentist-self-12B.anno: OK
workdir/.reads.dentist-self-12B.data: OK
workdir/.reads.dentist-self-1B.anno: OK
workdir/.reads.dentist-self-1B.data: OK
workdir/.reads.dentist-self-2B.anno: OK
workdir/.reads.dentist-self-2B.data: OK
workdir/.reads.dentist-self-3B.anno: OK
workdir/.reads.dentist-self-3B.data: OK
workdir/.reads.dentist-self-4B.anno: OK
workdir/.reads.dentist-self-4B.data: OK
workdir/.reads.dentist-self-5B.anno: OK
workdir/.reads.dentist-self-5B.data: OK
workdir/.reads.dentist-self-6B.anno: OK
workdir/.reads.dentist-self-6B.data: OK
workdir/.reads.dentist-self-7B.anno: OK
workdir/.reads.dentist-self-7B.data: OK
workdir/.reads.dentist-self-8B.anno: OK
workdir/.reads.dentist-self-8B.data: OK
workdir/.reads.dentist-self-9B.anno: OK
workdir/.reads.dentist-self-9B.data: OK
workdir/.reads.idx: OK
workdir/.reads.tan-10B.anno: OK
workdir/.reads.tan-10B.data: OK
workdir/.reads.tan-11B.anno: OK
workdir/.reads.tan-11B.data: OK
workdir/.reads.tan-12B.anno: OK
workdir/.reads.tan-12B.data: OK
workdir/.reads.tan-1B.anno: OK
workdir/.reads.tan-1B.data: OK
workdir/.reads.tan-2B.anno: OK
workdir/.reads.tan-2B.data: OK
workdir/.reads.tan-3B.anno: OK
workdir/.reads.tan-3B.data: OK
workdir/.reads.tan-4B.anno: OK
workdir/.reads.tan-4B.data: OK
workdir/.reads.tan-5B.anno: OK
workdir/.reads.tan-5B.data: OK
workdir/.reads.tan-6B.anno: OK
workdir/.reads.tan-6B.data: OK
workdir/.reads.tan-7B.anno: OK
workdir/.reads.tan-7B.data: OK
workdir/.reads.tan-8B.anno: OK
workdir/.reads.tan-8B.data: OK
workdir/.reads.tan-9B.anno: OK
workdir/.reads.tan-9B.data: OK
workdir/assembly-test.dam: OK
workdir/gap-closed-preliminary.dam: FAILED
workdir/gap-closed-preliminary.fasta: FAILED
workdir/reads.db: OK
workdir/validation-report.json: OK
md5sum: WARNING: 21 computed checksums did NOT match

```
